---
- hosts: Testnode
  sudo: yes
  tasks:
    - name: Download jetty
      get_url:
        url: http://repo2.maven.org/maven2/org/eclipse/jetty/jetty-distribution/9.0.6.v20130930/jetty-distribution-9.0.6.v20130930.zip
        dest: /opt     

    - unarchive: 
        src: /opt/jetty-distribution-9.0.6.v20130930.zip
        dest: /opt/jetty
        owner: root
        group: root

    - name: insert lines to jetty.sh
      blockinfile:
        path: /opt/jetty/bin/jetty.sh
        insertafter: EOF
        content: |
          JETTY_HOME=/opt/jetty
          JETTY_USER=root
          JETTY_LOGS=/opt/jetty/logs

    - file:
        src: /opt/jetty/bin/jetty.sh
        dest: /etc/init.d/jetty
        state: link

    - name: update
      action: shell sudo update-rc.d jetty defaults
